version: "3"

services:
  backend:
    image: gcr.io/hiring-278615/reposerver:v1.1
    container_name: backend
    expose:
      - 8080
    ports:
      - 8080:8080

  frontend:
    image: docker.io/sarahyucodes/github-api-coding-challenge:latest
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - backend